receivers:
  - name: slack
    slack_configs:
      - api_url: https://hooks.slack.com/services/<webhook-id>
        channel: '#<channel-name>'
        send_resolved: true
        text: '{{ .CommonAnnotations.description }}'
        username: Prometheus
route:
  receiver: slack
