global:
  evaluation_interval: 15s
  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: docker-host-alpha
  scrape_interval: 15s
# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - targets.rules
  - hosts.rules
  - containers.rules
# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: nodeexporter
    scrape_interval: 5s
    static_configs:
      - targets:
          - nodeexporter:9100
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets:
          - cadvisor:8080
  - job_name: prometheus
    scrape_interval: 10s
    static_configs:
      - targets:
          - localhost:9090
        # sample scrape configuration for AWS EC2
  - ec2_sd_configs:
      - port: 9100
        region: us-east-1
    job_name: nodeexporter
    relabel_configs:
      # Only monitor instances which have a tag called Monitoring "Monitoring"
      - action: keep
        regex: On
        source_labels:
          - __meta_ec2_tag_Monitoring
  - ec2_sd_configs:
      - port: 9010
        region: us-east-1
    job_name: cadvisor
    relabel_configs:
      # Only monitor instances which have a tag called Monitoring "Monitoring"
      - action: keep
        regex: On
        source_labels:
          - __meta_ec2_tag_Monitoring
